version: "3.8"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_HOST=${QDRANT_HOST}         # Full Qdrant Cloud URL (e.g., https://yourcluster.qdrant.io)
      - QDRANT_API_KEY=${QDRANT_API_KEY}   # API Key from Qdrant Cloud
